Added conf file, and use it

diff --git a/packaging/debian/steam/etc/init.d/steam b/packaging/debian/steam/etc/init.d/steam
--- a/packaging/debian/steam/etc/init.d/steam
+++ b/packaging/debian/steam/etc/init.d/steam
@@ -21,20 +21,60 @@ STEAM_USER=steam
 STEAM_GROUP=steam
 PIDFILE=/var/run/steam.pid
 
+. /etc/steam/steam.conf
+
 case "$1" in
   set-admin)
     # Interactively prompt to set local steam admin username and password.
     $DAEMON --set-admin
+    if [ $? -ne 0 ]; then
+      echo "ERROR: setting admin credentials failed"
+      exit 2
+    fi
+    ;;
+  create-self-signed-cert)
+    # Helper to get set up quickly if you don't have a real certificate from your IT department.
+    openssl req -x509 -newkey rsa:4096 -keyout /etc/steam/private_key.pem -out /etc/steam/cert.pem -days 3650 -nodes -subj "/O=steam"
+    if [ $? -ne 0 ]; then
+      echo "ERROR: cert creation failed"
+      exit 2
+    fi
     ;;
   start)
     logger -s -p INFO "INFO: Starting H2O Steam..."
+
     pidof steam
     RC=$?
     if [ $RC -ne 1 ]; then
       logger -s -p ERR "ERROR: Steam is already running"
       exit 2
     fi
-    start-stop-daemon --start --make-pidfile --pidfile $PIDFILE --background --startas /bin/bash -- -c "exec $DAEMON serve master --working-directory=$H2ODIR/var/master >> /var/log/steam.log 2>&1"
+
+    if [ ! -f $STEAM_WEB_TLS_CERT_PATH ]; then
+      logger -s -p ERR "ERROR: no cert ($STEAM_WEB_TLS_CERT_PATH)"
+      echo ""
+      echo "Try $0 create-self-signed-cert"
+      exit 2
+    fi
+
+    if [ ! -f $STEAM_WEB_TLS_PRIVATE_KEY_PATH ]; then
+      logger -s -p ERR "ERROR: no key ($STEAM_WEB_TLS_PRIVATE_KEY_PATH)"
+      echo ""
+      echo "Try $0 create-self-signed-cert"
+      exit 2
+    fi
+
+    if [ `id -u` -ne 0 ]; then
+      logger -s -p ERR "ERROR: Must be root"
+      exit 2
+    fi
+
+    start-stop-daemon \
+      --start \
+      --make-pidfile --pidfile $PIDFILE \
+      --background \
+      --startas /bin/bash -- -c "exec $DAEMON serve master --web-address=:$STEAM_HTTPS_PORT --cluster-proxy-address=:$STEAM_PROXY_HTTPS_PORT --web-tls-cert-path=$STEAM_WEB_TLS_CERT_PATH --web-tls-key-path=$STEAM_WEB_TLS_PRIVATE_KEY_PATH --working-directory=$H2ODIR/var/master >> /var/log/steam.log 2>&1"
+
     RC=$?
     if [ $RC -ne 0 ]; then
       logger -s -p ERR "ERROR: Start failed (RC is $RC)"
