More init script tweaks.

diff --git a/packaging/debian/steam/etc/init.d/steam b/packaging/debian/steam/etc/init.d/steam
--- a/packaging/debian/steam/etc/init.d/steam
+++ b/packaging/debian/steam/etc/init.d/steam
@@ -1,25 +1,20 @@
 #!/bin/sh
-# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
-#if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
-#    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
-#fi
+
 ### BEGIN INIT INFO
 # Provides:          steam
 # Required-Start:    $remote_fs $syslog
 # Required-Stop:     $remote_fs $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: H2O Steam platform
-# Description:       H2O Steam platform
+# Short-Description: H2O Steam service
+# Description:       H2O Steam service
 #                    <...>
 #                    <...>
 ### END INIT INFO
 
 # Author: Steam Team <steam@h2o.ai>
-# Code "leveraged" from other init.d scripts.
 
 PATH=/bin:/usr/bin:/sbin:/usr/sbin
-DESC="steam"
 H2ODIR=/opt/h2oai/steam
 DAEMON=$H2ODIR/steam
 STEAM_USER=steam
@@ -27,35 +22,50 @@ STEAM_GROUP=steam
 PIDFILE=/var/run/steam.pid
 
 case "$1" in
-  set-admin-password)
-	$DAEMON --set-admin-password
+  set-admin)
+    # Interactively prompt to set local steam admin username and password.
+    $DAEMON --set-admin
     ;;
   start)
-	logger "Starting h2o steam" "steam"
-	start-stop-daemon --start --make-pidfile --pidfile $PIDFILE --background --startas /bin/bash -- -c "exec $DAEMON serve master --working-directory=$H2ODIR/var/master >> /var/log/steam.log 2>&1"
-	logger $?
+    logger -s -p INFO "INFO: Starting H2O Steam..."
+    pidof steam
+    RC=$?
+    if [ $RC -ne 1 ]; then
+      logger -s -p ERR "ERROR: Steam is already running"
+      exit 2
+    fi
+    start-stop-daemon --start --make-pidfile --pidfile $PIDFILE --background --startas /bin/bash -- -c "exec $DAEMON serve master --working-directory=$H2ODIR/var/master >> /var/log/steam.log 2>&1"
+    RC=$?
+    if [ $RC -ne 0 ]; then
+      logger -s -p ERR "ERROR: Start failed (RC is $RC)"
+      exit 2
+    else
+      logger -s -p INFO "INFO: Started"
+    fi
     ;;
   stop)
-	logger "Stopping h2o steam" "steam"
-	start-stop-daemon --stop --pidfile  $PIDFILE
-	logger $?
+    logger -s -p INFO "INFO: Stopping H2O Steam..."
+    start-stop-daemon --oknodo --stop --pidfile $PIDFILE
+    RC=$?
+    if [ $RC -ne 0 ]; then
+      logger -s -p WARN "WARN: Stop failed (RC is $RC), but ignoring"
+    else
+      rm -f $PIDFILE
+      logger -s -p INFO "INFO: Stopped"
+    fi
     ;;
-  status)
-	if pidofproc -p $PIDFILE $DAEMON >/dev/null 2>&1; then
-	    echo "$DAEMON is running";
-	    exit 0;
-	else
-	    echo "$DAEMON is NOT running";
-	    if test -f $PIDFILE; then exit 2; fi
-	    exit 3;
-	fi
+  force-stop)
+    logger -s -p INFO "INFO: Force stopping H2O Steam..."
+    killall steam
+    rm -f $PIDFILE
+    logger -s -p INFO "INFO: Stopped"
     ;;
   force-reload|restart)
     $0 stop
     $0 start
     ;;
   *)
-    echo "Usage: /etc/init.d/steam {start|stop|restart|force-reload}"
+    echo "Usage: /etc/init.d/steam {set-admin|start|stop|force-stop|restart|force-reload}"
     exit 1
     ;;
 esac
