Uncomment --check-admin

diff --git a/packaging/debian/steam/etc/init.d/steam b/packaging/debian/steam/etc/init.d/steam
--- a/packaging/debian/steam/etc/init.d/steam
+++ b/packaging/debian/steam/etc/init.d/steam
@@ -69,13 +69,13 @@ case "$1" in
       exit 2
     fi
 
-#    $DAEMON --check-admin
-#    if [ $? -ne 0 ]; then
-#      logger -s -p ERR "ERROR: no admin credentials set"
-#      echo ""
-#      echo "Try $0 set-admin"
-#      exit 2
-#    fi
+    $DAEMON --check-admin
+    if [ $? -ne 0 ]; then
+      logger -s -p ERR "ERROR: no admin credentials set"
+      echo ""
+      echo "Try $0 set-admin"
+      exit 2
+    fi
 
     start-stop-daemon \
       --start \
